import numpy as np
import sys
import time
a=np.array([(1,2,3),(4,5,6)])
print(a)
S=range(3000)
dict={'a':'3'}
print(sys.getsizeof(5)*len(S))
size=100000
l1=range(size)
l2=range(size)
a1=np.arange(size)
a2=np.arange(size)
start=time.time()
result=[(x,y) for x,y in zip(l1,l2)]
print((time.time()-start)*1000)
start=time.time()
result=a1+a2
print((time.time()-start)*1000)
print(dict)
print(len(dict))
print(a.ndim)
print(a.itemsize)
print(a.dtype)
print(np.sqrt(a))
print(np.std(a))
print(a.sum(axis=0))
print(a.sum(axis=1))
print(a.size)
print(a.shape)
print(a.reshape(2,3))
q=np.linspace(1,3,5)
print(q)
print(a[0:,2])
print(a.sum())
print(a.max())
print(a.min())
a1=np.array([(1,2,3),(2,3,4)])
a2=np.array([(2,5,6),(1,6,7)])
print(a1+a2)
print(a1-a2)
print(a1*a2)
print(a1/a2)
print(a1%a2)
print(np.vstack((a1,a2)))
print(np.hstack((a1,a2)))